### ISSUE TITLE
API validation fails and config retrieval not working per store on Magento site with several websites

### ISSUE THREAD

**Issue by alexpoletaev** [sailthru/sailthru-magento2-extension#10]
**Preconditions:**
- Magento site with several websites

**Actual result:**
- The API key can be confirmed only if it was filled for the 'default' scope
- System configuration value is returned only for the 'default' scope

**Expected result:**
- The API key successfully validated when it was filled per website scope
- System configuration value is returned per store/website scope

**Comment by silverman63** [comment]
Merged your branch. Release 1.0.1 should address the concern. Closing.
