### ISSUE TITLE
Wrong sender name/email in reset password email via admin in multistore

### ISSUE THREAD

**Issue by klakovsky** [sailthru/sailthru-magento2-extension#29]
Preconditions:
Different email Senders configured for different websites:
Configuration > General > Store Email Addresses > Sales Representative > Sender Name/Email

Steps to reproduce:
Log in to the admin panel
Open any customer (with non-default store_id)
Click "Reset Password"
Check customer mailbox

Actual result:
Customer reset password emails send from Sender of the default website

Expected result:
Customer reset password emails send from Sender of the website the customer was assigned.

Notes:
We use workaround with plugin for:
Magento\Customer\Model\EmailNotificationInterface: 

getSettingsVal method of Api.php helper checks store/website in request object, but when send email from admin panel, there is no order store code/id in request so all configs will be taken for default store.

**Comment by silverman63** [comment]
Hi @klakovsky are you still observing this issue? Theoretically, our ScopeResolver should've fixed this. https://github.com/sailthru/sailthru-magento2-extension/blob/master/Helper/ScopeResolver.php
