### ISSUE TITLE
Broken: Update customer email address

### ISSUE THREAD

**Issue by robyerevan** [sailthru/sailthru-magento2-extension#56]
magento 2.3.1

Steps to reproduce:

- Sign in as customer
- Navigate to My Account
- Edit account information
- Check "Change Email"
- Change email address
- Save

**Expected result:**
- Account information saved

**Actual result:**
- Error displayed "We can't save the customer"
- Error thrown by sailthru
`main.CRITICAL: Exception message: Notice: Undefined offset: 1 in vendor/sailthru/sailthru-magento2-extension/Mail/Template.php on line 170`

This happens cause $directiveString[1] is undefined, cause [template has no vars @vars {} ](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/Customer/view/frontend/email/change_email.html)
```php
                    $this->templateDirectives[strtolower(str_replace(' ', '_', $directiveString[1]))] = str_replace(
                        ' ',
                        '',
                        $directiveString[0]
                    );
```

**Comment by sshymko** [comment]
Why does Sailthru implement a custom way of parsing Magento templates? It should reuse the core email template parsing logic to not introduce issues like this one.

**Comment by robyerevan** [comment]
Proposed quick fix 
https://github.com/sailthru/sailthru-magento2-extension/pull/57/files

**Comment by silverman63** [comment]
Hi all, we're currently looking into this. Are you currently using 2.3.3 in production?

**Comment by sshymko** [comment]
We're currently on 2.3.1

**Comment by silverman63** [comment]
@robyerevan can you confirm if you are using 2.3.3 in production, and if not your timeline for 2.3.3?

**Comment by robyerevan** [comment]
@silverman63  we are on Magento 2.3.1
We will not upgrade during holidays ...  next year maybe

**Comment by brownac** [comment]
@robyerevan I'm QA'ing the PR you opened, and noticed that when I run through the steps again, I get the following error:
```
 Parse error: syntax error, unexpected 'continue' (T_CONTINUE) in /var/www/html/vendor/sailthru/sailthru-magento2-extension/Mail/Template.php on line 169
```
When I refresh the error page and resend the form data, it works.

I ran into [this](https://stackoverflow.com/questions/18050071/php-parse-syntax-errors-and-how-to-solve-them/51786865#51786865), might it having something to do with that error?

**Comment by brownac** [comment]
@robyerevan this was merged and released today. Thank you for your help in fixing this!
