### ISSUE TITLE
Sailthru Error closing orders

### ISSUE THREAD

**Issue by eguardado-one** [sailthru/sailthru-magento2-extension#65]
Preconditions (*)
Tested on Magento 2.3.4
XTENTO order import export installed
composer.json:19: "sailthru/sailthru-magento2-extension": "^2.0"

Steps to reproduce (*)
Closing orders with XTENTO either manually or through cron

Expected result (*)
Order should close in Magento and a Ship confirmation email should be sent to the customer

Actual result (*)
Error, orders do not close

Fatal error: Uncaught Error: Call to a member function getName() on null in vendor/sailthru/sailthru-magento2-extension/Helper/Shipment.php:89 Stack trace: #0 public_html/vendor/sailthru/sailthru-magento2-extension/Helper/Shipment.php(40): Sailthru\MageSail\Helper\Shipment->getShippingItems(Array) #1 public_html/vendor/sailthru/sailthru-magento2-extension/Helper/Settings.php(321): Sailthru\MageSail\Helper\Shipment->getCustomVariables(Object(Magento\Sales\Model\Order\Shipment\Interceptor)) #2 public_html/vendor/sailthru/sailthru-magento2-extension/Mail/Transport.php(118): Sailthru\MageSail\Helper\Settings->getTemplateAdditionalVariables('sales_email_shi...', Array) #3 public_html/generated/code/Sailthru/MageSail/Mail/Transport/Interceptor.php(37): Sailthru\MageSail\Mail\Transport->sendViaAPI(Array, '1') #4 public_html/vendor/sailthru/sailthru-magento2-extension/Mail/Transport.php(8 in public_html/vendor/sailthru/sailthru-magento2-extension/Helper/Shipment.php on line 89

We added a hotfix, but this of course is not long term.  Could you please provide a fix?

Link to code check for getName if it is null

![sailthru-image001](https://user-images.githubusercontent.com/53453704/79878300-8529a780-83aa-11ea-8496-f3addab5cbc0.png)

**Comment by lindsaycooper** [comment]
This is fixed in https://github.com/sailthru/sailthru-magento2-extension/issues/65
