### ISSUE TITLE
Repeated Requests

### ISSUE THREAD

**Issue by yavuz** [sailthru/sailthru-magento2-extension#71]
Hi;

Some mail request return from sailthru like this.

```
2020-09-07T06:31:05+00:00 ERR (3): array (
  'error' => 'POST /send',
  'scope' => 'default store',
  'code' => 32,
  'message' => 'Email test@test.test has opted out of all email delivery',
)

2020-09-07T06:31:05+00:00 ERR (3): array (
  'error' => 'POST /send',
  'scope' => 'default store',
  'code' => 35,
  'message' => 'Email test@test.test is a known hardbounce',
)

2020-09-07T06:31:07+00:00 ERR (3): array (
  'error' => 'POST /send',
  'scope' => 'default store',
  'code' => 37,
  'message' => 'Email test@test.test has opted out of delivery from all templates except the basic ones',
)
```

It continues non-stop. How can I stop it from trying them.

Anyone have any idea about this?

**Comment by silverman63** [comment]
Hi @yavuz, is `test@test.test` a placeholder here or the real value?

**Comment by silverman63** [comment]
@yavuz a few questions / answers:

* What would your ideal workflow be for hardbounces or users that have opted out all messaging? Note this is a user-specified decision opt-out decision usually.
* Regarding error code 37, you can consider marking the templates basic in the Sailthru UI. If this is for a purely transactional use case (no marketing) this should be safe to do. If it involves any form of marketing, feel free to get advice regarding basic templates from your CSM or Support. If marked basic, it'll be able to send to customers who've opted out of marketing messages.

**Comment by yavuz** [comment]
- Do I need to handle these manually?
- I will mark them as transactional emails.

Also, I saw this log below. It's trying to send email to a incorrect email address. Should I also handle this situtation?

```
2020-09-09T09:49:06+00:00 ERR (3): array (
  'error' => 'POST /send',
  'scope' => 'default store',
  'code' => 34,
  'message' => 'Email test@gmail.con may not be emailed',
)
```

Thanks.

**Comment by yavuz** [comment]
I want to override MageClient class for handling these error codes. But whatever I did I couldn't override it.

I added this to my module. But it still calls the httpRequest method in parent class.

di.xml

```xml
<preference for="Sailthru\MageSail\MageClient" type="MyModule\Sailthru\MageClient" />
```

MageClient.php

```php
<?php
namespace MyModule\Sailthru;

use Magento\Framework\Module\ModuleListInterface;
use Sailthru\MageSail\Helper\ScopeResolver;
use Sailthru\MageSail\Logger;

class MageClient extends \Sailthru\MageSail\MageClient {
    public $_eventType = null;

    /** @var string */
    private $version;

    /** @var Logger  */
    private $logger;

    /** @var ScopeResolver */
    private $scopeResolver;

    public function __construct($api_key, $secret, $version, Logger $logger, ScopeResolver $scopeResolver)
    {
        $this->logger = $logger;
        $this->scopeResolver = $scopeResolver;
        $this->version = $version;
        parent::__construct($api_key, $secret, $version, $logger, $scopeResolver);
    }

    protected function httpRequest($action, $data, $method = 'POST', $options = [])
    {
        $logAction = "{$method} /{$action}";
        $scope= $this->scopeResolver->getScope();
        $scopeString = "{$scope[0]} {$scope[1]}";
        $this->logger->info([
            'action'            => $logAction,
            'event_type'        => $this->_eventType,
            'scope'             => $scopeString,
            'http_request_type' => $this->http_request_type,
            'body'              => $data['json']
        ]);
        try {
            $response = parent::httpRequest($action, $data, $method, $options);
            $this->logger->info([
                'action_response'  => $logAction,
                'event_type '      => $this->_eventType,
                'scope'            => $scopeString,
                'response'         => !$this->truncateResponse($method, $action) ? $response : "<TRUNCATED>"
            ]);
            return $response;
        } catch (\Sailthru_Client_Exception $e) {
            $this->logger->err([
                'error'    => $logAction,
                'scope'    => $scopeString,
                'code'     => $e->getCode(),
                'message'  => $e->getMessage(),
            ]);

            // 32 => Email test@test.test has opted out of all email delivery
            $code = $e->getCode();
            if($code == '32') {
                  // mycode
            }

            throw $e;
        }
    }

    private function truncateResponse($method, $action)
    {
        return in_array([$method, $action], self::$TRUNCATE_RESPONSES);
    }
}
```

**Comment by silverman63** [comment]
Hi @yavuz, we can't really offer much more than guidance regarding custom implementations.

I'm curious about what your goal is? For what reason would you not want to know this?

Also tagging @giraclion who may be able to work with you on a solution. His agency is extremely familiar with and contributes to the plugin.

**Comment by mapetek** [comment]
Hi @silverman63,

Our goal is to flag users who opted-out from emails so Magento will not try sending emails to them forever. That's why we're trying to extend the extension. We already did it, but our class is only being called when we test it via ObjectManager. I suspect that using an external library in your extension may be causing this issue. We simply want to extend this extension and use it. Any ideas?

Thanks!

**Comment by silverman63** [comment]
@mapetek I see. That makes sense, though it can be a little tricky. So are you planning to write an attribute to the customer representing this?

**Comment by silverman63** [comment]
You may need to configure this file which acts as a factory for the MageClient https://github.com/sailthru/sailthru-magento2-extension/blob/master/Helper/ClientManager.php

**Comment by mapetek** [comment]
@silverman63 Thanks, we'll try extending the ClientManager class. 
If the user opted-out or the emails hard bounce, we're planning to mark those as sent for now. I'm not sure if we make another fix later.
