### ISSUE TITLE
Exception during Magento installation

### ISSUE THREAD

**Issue by alexpoletaev** [sailthru/sailthru-magento2-extension#8]
**Steps to reproduce:**
- `composer install`
- `composer require sailthru/sailthru-magento2-extension`
- install Magento site using web interface

**Actual result:**
installation crashes with error:
      `Module 'Sailthru_MageSail':
Installing data... 
[ERROR] exception 'Magento\Framework\Exception\AlreadyExistsException' with message 'Attribute with the same code already exists.' in ...`

**Expected result:**
- successfully installed Magento site

**Comment by silverman63** [comment]
Merged your branch. Release 1.0.1 should address the concern. Closing.
