### ISSUE TITLE
Support for Magento 2.4.5 and PHP 8.1

### ISSUE THREAD

**Issue by yavuz** [sailthru/sailthru-magento2-extension#92]
Hi, any updates for support magento 2.4.5?

Thanks

**Comment by giraclion** [comment]
Hi @yavuz,

Compatibility changes will be released by end of Jan 2022. This will include latest Magento version support as well as PHP 8.1 support.

**Comment by yavuz** [comment]
thank you. I'll be waiting it.

**Comment by yavuz** [comment]
thanks for 2.4.0 version. Its works now
