### ISSUE TITLE
Can't Enable Module

### ISSUE THREAD

**Issue by cbartellds** [sailthru/sailthru-magento2-extension#94]
After installing the module via composer, when I try to run "bin/magento module:enable Sailthru_MageSail", I get the error "Unknown module(s): 'Sailthru_MageSail'.

The files are in my vendor folder.

![Screen Shot 2023-06-02 at 1 57 37 PM](https://github.com/sailthru/sailthru-magento2-extension/assets/36934689/80b6fcbc-1f6b-49f2-a852-299db1cfeee7)

And Sailthru is in my composer.json file.

![Screen Shot 2023-06-02 at 1 58 33 PM](https://github.com/sailthru/sailthru-magento2-extension/assets/36934689/bc579c6f-8bbe-474d-bfdf-6b83a90aa456)

My Magento version is 2.4.6.

**Comment by cbartellds** [comment]
Figured out that it has to do with how my local site is set up. I needed to "copy" the vendor files into my docker container.

**Comment by azinger-sailthru** [comment]
Thanks for following up on this and for bringing it to our attention (even if there was no issue at the end)!
